version: '3.8'
services: 
  database:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: posign
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306"
    networks:
      vpcbr: 
        ipv4_address: 172.23.0.2
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_ABSOLUTE_URI: http://${HOSTNAME}/posignpma/
    volumes:
      - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadminposign.rule=PathPrefix(`/posignpma`)
      - traefik.http.routers.phpmyadminposign.middlewares=strip-phpmyadminposign-prefix
      - traefik.http.middlewares.strip-phpmyadminposign-prefix.stripPrefix.prefixes=/posignpma
      - traefik.http.routers.phpmyadminposign.entrypoints=web
    networks:
      vpcbr:
        ipv4_address: 172.23.0.3
    depends_on:
      - database

networks:
 vpcbr: 
  driver: bridge
  ipam:
    config:
      - subnet: 172.23.0.0/16
      - gateway: 172.23.0.1
    


      
      